<?php

namespace backend\models;

use backend\components\User;
use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $date
 * @property string $creator
 * @property int $rubric_id
 * @property string $short_content
 * @property int $status
 */
class News extends \yii\db\ActiveRecord
{
    public $image;
    const MODER = 0;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title','rubric_id'], 'required'],
            [['content','short_content'], 'string'],
            [['date'], 'safe'],
            [['rubric_id','status'], 'integer'],
            [['image'], 'safe'],
            [['image'], 'file', 'extensions'=>'jpg, gif, png'],
            [['image'], 'file', 'maxSize'=>'100000'],
            [['title', 'creator','img'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Ид',
            'title' => 'Заголовок',
            'content' => '',
            'date' => 'Дата',
            'creator' => 'Автор',
            'rubric_id' => 'Рубрика',
            'image' => 'Картинка новости',
            'short_content' => 'Кароткая описание',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->date == ''){
            $this->date = date("Y-m-d",time());
        } else {
            $this->date = date("Y-m-d",strtotime($this->date));
        }
        $this->image = UploadedFile::getInstance($this, 'image');
        if (!empty($this->image)) {

            $fileName = rand(0, 999) . '_' . time() . '.' . $this->image->extension;
            if (!is_dir(Yii::getAlias('@frontend') . '/web/uploads/news/')) {
                mkdir(Yii::getAlias('@frontend') . '/web/uploads/news/');
            }
            $this->image->saveAs(Yii::getAlias('@frontend') . '/web/uploads/news/' . $fileName);
            $this->img = $fileName;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if(User::getRoleName() == 'admin'){
            $this->status = 2;
        } else {
            $this->status = self::MODER;
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
